# Model configuration
model:
  num_cascades: 12
  sens_chans: 32
  chans: 96

# Optimization configuration
optimization:
  learning_rate: 6e-4
  lr_gamma: 0.98
  warmup_epochs: 3
  weight_decay: 1e-3

# Data configuration
data:
  train_csv: # Provide the training .csv path
  val_csv: # Provide the validation .csv path
  train_batch_size: 8
  val_batch_size: 8
  num_workers: 4
  
# Training configuration
training:
  max_epochs: 200
  log_every_n_steps: 20
  loss_function: ssim
  
# Checkpoint configuration
checkpoint:
  dirpath: ./checkpoints
  filename: PSIRNet_{epoch}
  save_top_k: 5
  every_n_epochs: 1
  save_on_train_epoch_end: true
  resume_from: null
  monitor: "val_ssim"
  mode: "max"

# Logger
logger:
  project: PSIRNet
  entity: # Enter your wandb entity
  name: psirnet-large
  save_dir: wandb_logs

# Hardware configuration
hardware:
  accelerator: gpu
  devices: 8
  strategy: ddp
  num_nodes: 8
